### ISSUE TITLE
【🐛Bug】【1.21-1.21.1】Toggling "Mirrored" option makes paperdoll or the config screen disappear

### ISSUE THREAD

**Issue by asrieldashie** [AyameMC/Ayame-PaperDoll#3]
https://github.com/user-attachments/assets/cd766980-0929-4bc6-8299-810c41e19ef9

**Comment by HappyRespawnanchor** [comment]
success was able to be reproduced in v4.0.1
i will fix it in next version
until that, you can rollback to v4.0.0/v4.1.0 :)

**Comment by HappyRespawnanchor** [comment]
Fixed in v4.0.2 :)
